name: Build Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Cache Gradle (dependencies + wrapper + build cache)
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 3. Set up JDK (17 for frontend)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4. Make Gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5. Build with Gradle (with optimizations)
      - name: Build with Gradle
        run: ./gradlew clean build --daemon --parallel --configure-on-demand --configuration-cache
